package com.abbcc.pojo;

/**
 * Dljmsx generated by MyEclipse Persistence Tools
 */

public class Dljmsx implements java.io.Serializable {

	// Fields

	private Integer dljmsxid;

	private Integer hyjbxxid;

	private String pp;

	private String jbtz;

	private String bzje;

	private String jmf;

	private String jmqy;

	private String ppfyd;

	private String yjhbr;

	private String yjhbzq;

	private String txqsyf;

	private String htqx;

	private String jmszs;

	private String txjysj;

	private String jyms;

	private String fzms;

	private String xxsm;

	private String tp1;

	private String tp2;

	private String tp3;

	private String xxyxq;

	private String sqsj;

	private String sfyx;

	private String scsj;

	// Constructors

	/** default constructor */
	public Dljmsx() {
	}

	/** full constructor */
	public Dljmsx(Integer hyjbxxid, String pp, String jbtz, String bzje,
			String jmf, String jmqy, String ppfyd, String yjhbr, String yjhbzq,
			String txqsyf, String htqx, String jmszs, String txjysj,
			String jyms, String fzms, String xxsm, String tp1, String tp2,
			String tp3, String xxyxq, String sqsj, String sfyx, String scsj) {
		this.hyjbxxid = hyjbxxid;
		this.pp = pp;
		this.jbtz = jbtz;
		this.bzje = bzje;
		this.jmf = jmf;
		this.jmqy = jmqy;
		this.ppfyd = ppfyd;
		this.yjhbr = yjhbr;
		this.yjhbzq = yjhbzq;
		this.txqsyf = txqsyf;
		this.htqx = htqx;
		this.jmszs = jmszs;
		this.txjysj = txjysj;
		this.jyms = jyms;
		this.fzms = fzms;
		this.xxsm = xxsm;
		this.tp1 = tp1;
		this.tp2 = tp2;
		this.tp3 = tp3;
		this.xxyxq = xxyxq;
		this.sqsj = sqsj;
		this.sfyx = sfyx;
		this.scsj = scsj;
	}

	// Property accessors

	public Integer getDljmsxid() {
		return this.dljmsxid;
	}

	public void setDljmsxid(Integer dljmsxid) {
		this.dljmsxid = dljmsxid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getPp() {
		return this.pp;
	}

	public void setPp(String pp) {
		this.pp = pp;
	}

	public String getJbtz() {
		return this.jbtz;
	}

	public void setJbtz(String jbtz) {
		this.jbtz = jbtz;
	}

	public String getBzje() {
		return this.bzje;
	}

	public void setBzje(String bzje) {
		this.bzje = bzje;
	}

	public String getJmf() {
		return this.jmf;
	}

	public void setJmf(String jmf) {
		this.jmf = jmf;
	}

	public String getJmqy() {
		return this.jmqy;
	}

	public void setJmqy(String jmqy) {
		this.jmqy = jmqy;
	}

	public String getPpfyd() {
		return this.ppfyd;
	}

	public void setPpfyd(String ppfyd) {
		this.ppfyd = ppfyd;
	}

	public String getYjhbr() {
		return this.yjhbr;
	}

	public void setYjhbr(String yjhbr) {
		this.yjhbr = yjhbr;
	}

	public String getYjhbzq() {
		return this.yjhbzq;
	}

	public void setYjhbzq(String yjhbzq) {
		this.yjhbzq = yjhbzq;
	}

	public String getTxqsyf() {
		return this.txqsyf;
	}

	public void setTxqsyf(String txqsyf) {
		this.txqsyf = txqsyf;
	}

	public String getHtqx() {
		return this.htqx;
	}

	public void setHtqx(String htqx) {
		this.htqx = htqx;
	}

	public String getJmszs() {
		return this.jmszs;
	}

	public void setJmszs(String jmszs) {
		this.jmszs = jmszs;
	}

	public String getTxjysj() {
		return this.txjysj;
	}

	public void setTxjysj(String txjysj) {
		this.txjysj = txjysj;
	}

	public String getJyms() {
		return this.jyms;
	}

	public void setJyms(String jyms) {
		this.jyms = jyms;
	}

	public String getFzms() {
		return this.fzms;
	}

	public void setFzms(String fzms) {
		this.fzms = fzms;
	}

	public String getXxsm() {
		return this.xxsm;
	}

	public void setXxsm(String xxsm) {
		this.xxsm = xxsm;
	}

	public String getTp1() {
		return this.tp1;
	}

	public void setTp1(String tp1) {
		this.tp1 = tp1;
	}

	public String getTp2() {
		return this.tp2;
	}

	public void setTp2(String tp2) {
		this.tp2 = tp2;
	}

	public String getTp3() {
		return this.tp3;
	}

	public void setTp3(String tp3) {
		this.tp3 = tp3;
	}

	public String getXxyxq() {
		return this.xxyxq;
	}

	public void setXxyxq(String xxyxq) {
		this.xxyxq = xxyxq;
	}

	public String getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}

	public String getSfyx() {
		return this.sfyx;
	}

	public void setSfyx(String sfyx) {
		this.sfyx = sfyx;
	}

	public String getScsj() {
		return this.scsj;
	}

	public void setScsj(String scsj) {
		this.scsj = scsj;
	}

}