package com.abbcc.pojo;

/**
 * Hysh generated by MyEclipse Persistence Tools
 */

public class Hysh implements java.io.Serializable {

	// Fields

	private Integer glyid;

	private Integer hyjbxxid;

	private String zcsj;

	private String dqsj;

	private String zhdlsj;

	private String wdlts;

	private String zhdlip;

	private String sfsh;

	private String sfyfx;

	private String dlcs;

	private String ksrq;

	private String jsrq;

	private String cpdjtj;

	// Constructors

	/** default constructor */
	public Hysh() {
	}

	/** full constructor */
	public Hysh(Integer hyjbxxid, String zcsj, String dqsj, String zhdlsj,
			String wdlts, String zhdlip, String sfsh, String sfyfx,
			String dlcs, String ksrq, String jsrq, String cpdjtj) {
		this.hyjbxxid = hyjbxxid;
		this.zcsj = zcsj;
		this.dqsj = dqsj;
		this.zhdlsj = zhdlsj;
		this.wdlts = wdlts;
		this.zhdlip = zhdlip;
		this.sfsh = sfsh;
		this.sfyfx = sfyfx;
		this.dlcs = dlcs;
		this.ksrq = ksrq;
		this.jsrq = jsrq;
		this.cpdjtj = cpdjtj;
	}

	// Property accessors

	public Integer getGlyid() {
		return this.glyid;
	}

	public void setGlyid(Integer glyid) {
		this.glyid = glyid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getZcsj() {
		return this.zcsj;
	}

	public void setZcsj(String zcsj) {
		this.zcsj = zcsj;
	}

	public String getDqsj() {
		return this.dqsj;
	}

	public void setDqsj(String dqsj) {
		this.dqsj = dqsj;
	}

	public String getZhdlsj() {
		return this.zhdlsj;
	}

	public void setZhdlsj(String zhdlsj) {
		this.zhdlsj = zhdlsj;
	}

	public String getWdlts() {
		return this.wdlts;
	}

	public void setWdlts(String wdlts) {
		this.wdlts = wdlts;
	}

	public String getZhdlip() {
		return this.zhdlip;
	}

	public void setZhdlip(String zhdlip) {
		this.zhdlip = zhdlip;
	}

	public String getSfsh() {
		return this.sfsh;
	}

	public void setSfsh(String sfsh) {
		this.sfsh = sfsh;
	}

	public String getSfyfx() {
		return this.sfyfx;
	}

	public void setSfyfx(String sfyfx) {
		this.sfyfx = sfyfx;
	}

	public String getDlcs() {
		return this.dlcs;
	}

	public void setDlcs(String dlcs) {
		this.dlcs = dlcs;
	}

	public String getKsrq() {
		return this.ksrq;
	}

	public void setKsrq(String ksrq) {
		this.ksrq = ksrq;
	}

	public String getJsrq() {
		return this.jsrq;
	}

	public void setJsrq(String jsrq) {
		this.jsrq = jsrq;
	}

	public String getCpdjtj() {
		return this.cpdjtj;
	}

	public void setCpdjtj(String cpdjtj) {
		this.cpdjtj = cpdjtj;
	}

}