package com.abbcc.pojo;

/**
 * Jytj generated by MyEclipse Persistence Tools
 */

public class Jytj implements java.io.Serializable {

	// Fields

	/**
	 * 交易条件ID
	 */
	private Long jytjid;


	/**
	 * 会员ID
	 */
	private Integer hyjbxxid;
	
	private Long cpgqxxId;

	/**
	 * 计量单位
	 */
	private String jldw;

	/**
	 * 产品单价
	 */
	private String cpdj;

	/**
	 * 最小起订量
	 */
	private String zxqdl;

	/**
	 * 供货总量
	 */
	private String ghzl;

	/**
	 * 发货期限
	 */
	private String fhqx;

	/**
	 * 供应商类型
	 */
	private String gyslc;

	// Constructors

	/** default constructor */
	public Jytj() {
	}

	 

	// Property accessors

	public Long getJytjid() {
		return this.jytjid;
	}

	public void setJytjid(Long jytjid) {
		this.jytjid = jytjid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getCpdj() {
		return this.cpdj;
	}

	public void setCpdj(String cpdj) {
		this.cpdj = cpdj;
	}

	public String getZxqdl() {
		return this.zxqdl;
	}

	public void setZxqdl(String zxqdl) {
		this.zxqdl = zxqdl;
	}

	public String getGhzl() {
		return this.ghzl;
	}

	public void setGhzl(String ghzl) {
		this.ghzl = ghzl;
	}

	public String getFhqx() {
		return this.fhqx;
	}

	public void setFhqx(String fhqx) {
		this.fhqx = fhqx;
	}

	public String getGyslc() {
		return this.gyslc;
	}

	public void setGyslc(String gyslc) {
		this.gyslc = gyslc;
	}



	public Long getCpgqxxId() {
		return cpgqxxId;
	}



	public void setCpgqxxId(Long cpgqxxId) {
		this.cpgqxxId = cpgqxxId;
	}

}