package com.abbcc.pojo;

/**
 * Cpgqxx generated by MyEclipse Persistence Tools
 */

public class Cpgqxx implements java.io.Serializable {

	// Fields

	private Integer cpgqxxid;

	private Integer hyjbxxid;

	private String xxlx;

	private String cpmc;

	private String cpshlm;

	private String xxbt;

	private String cpsxid;

	private String xxsm;

	private String tp1;

	private String tp2;

	private String tp3;

	private String xxyxq;

	private String jytjid;

	private String sqsj;

	private String sfyx;

	private String scsj;

	// Constructors

	/** default constructor */
	public Cpgqxx() {
	}

	/** full constructor */
	public Cpgqxx(Integer hyjbxxid, String xxlx, String cpmc, String cpshlm,
			String xxbt, String cpsxid, String xxsm, String tp1, String tp2,
			String tp3, String xxyxq, String jytjid, String sqsj, String sfyx,
			String scsj) {
		this.hyjbxxid = hyjbxxid;
		this.xxlx = xxlx;
		this.cpmc = cpmc;
		this.cpshlm = cpshlm;
		this.xxbt = xxbt;
		this.cpsxid = cpsxid;
		this.xxsm = xxsm;
		this.tp1 = tp1;
		this.tp2 = tp2;
		this.tp3 = tp3;
		this.xxyxq = xxyxq;
		this.jytjid = jytjid;
		this.sqsj = sqsj;
		this.sfyx = sfyx;
		this.scsj = scsj;
	}

	// Property accessors

	public Integer getCpgqxxid() {
		return this.cpgqxxid;
	}

	public void setCpgqxxid(Integer cpgqxxid) {
		this.cpgqxxid = cpgqxxid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getXxlx() {
		return this.xxlx;
	}

	public void setXxlx(String xxlx) {
		this.xxlx = xxlx;
	}

	public String getCpmc() {
		return this.cpmc;
	}

	public void setCpmc(String cpmc) {
		this.cpmc = cpmc;
	}

	public String getCpshlm() {
		return this.cpshlm;
	}

	public void setCpshlm(String cpshlm) {
		this.cpshlm = cpshlm;
	}

	public String getXxbt() {
		return this.xxbt;
	}

	public void setXxbt(String xxbt) {
		this.xxbt = xxbt;
	}

	public String getCpsxid() {
		return this.cpsxid;
	}

	public void setCpsxid(String cpsxid) {
		this.cpsxid = cpsxid;
	}

	public String getXxsm() {
		return this.xxsm;
	}

	public void setXxsm(String xxsm) {
		this.xxsm = xxsm;
	}

	public String getTp1() {
		return this.tp1;
	}

	public void setTp1(String tp1) {
		this.tp1 = tp1;
	}

	public String getTp2() {
		return this.tp2;
	}

	public void setTp2(String tp2) {
		this.tp2 = tp2;
	}

	public String getTp3() {
		return this.tp3;
	}

	public void setTp3(String tp3) {
		this.tp3 = tp3;
	}

	public String getXxyxq() {
		return this.xxyxq;
	}

	public void setXxyxq(String xxyxq) {
		this.xxyxq = xxyxq;
	}

	public String getJytjid() {
		return this.jytjid;
	}

	public void setJytjid(String jytjid) {
		this.jytjid = jytjid;
	}

	public String getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}

	public String getSfyx() {
		return this.sfyx;
	}

	public void setSfyx(String sfyx) {
		this.sfyx = sfyx;
	}

	public String getScsj() {
		return this.scsj;
	}

	public void setScsj(String scsj) {
		this.scsj = scsj;
	}

}