package com.abbcc.pojo;

/**
 * Gsxxxx generated by MyEclipse Persistence Tools
 */

public class Gsxxxx implements java.io.Serializable {

	// Fields

	private Integer hyjbxxid;

	private String zycp;

	private String zyhy;

	private String jyms;

	private String qylx;

	private String gszcd;

	private String zyjydd;

	private String gsclsj;

	private String fddbr;

	private String nyye;

	private String ygrs;

	private String jypp;

	private String zczb;

	private String zykhq;

	private String zysc;

	private String ncke;

	private String njke;

	private String khyh;

	private String zh;

	private String oem;

	private String yfbmrs;

	private String ycl;

	private String cfmj;

	private String zlkz;

	private String gltxrz;

	private String gsjs;

	private String gstp;

	// Constructors

	/** default constructor */
	public Gsxxxx() {
	}

	/** full constructor */
	public Gsxxxx(Integer hyjbxxid, String zycp, String zyhy, String jyms,
			String qylx, String gszcd, String zyjydd, String gsclsj,
			String fddbr, String nyye, String ygrs, String jypp, String zczb,
			String zykhq, String zysc, String ncke, String njke, String khyh,
			String zh, String oem, String yfbmrs, String ycl, String cfmj,
			String zlkz, String gltxrz, String gsjs, String gstp) {
		this.hyjbxxid = hyjbxxid;
		this.zycp = zycp;
		this.zyhy = zyhy;
		this.jyms = jyms;
		this.qylx = qylx;
		this.gszcd = gszcd;
		this.zyjydd = zyjydd;
		this.gsclsj = gsclsj;
		this.fddbr = fddbr;
		this.nyye = nyye;
		this.ygrs = ygrs;
		this.jypp = jypp;
		this.zczb = zczb;
		this.zykhq = zykhq;
		this.zysc = zysc;
		this.ncke = ncke;
		this.njke = njke;
		this.khyh = khyh;
		this.zh = zh;
		this.oem = oem;
		this.yfbmrs = yfbmrs;
		this.ycl = ycl;
		this.cfmj = cfmj;
		this.zlkz = zlkz;
		this.gltxrz = gltxrz;
		this.gsjs = gsjs;
		this.gstp = gstp;
	}

	// Property accessors

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getZycp() {
		return this.zycp;
	}

	public void setZycp(String zycp) {
		this.zycp = zycp;
	}

	public String getZyhy() {
		return this.zyhy;
	}

	public void setZyhy(String zyhy) {
		this.zyhy = zyhy;
	}

	public String getJyms() {
		return this.jyms;
	}

	public void setJyms(String jyms) {
		this.jyms = jyms;
	}

	public String getQylx() {
		return this.qylx;
	}

	public void setQylx(String qylx) {
		this.qylx = qylx;
	}

	public String getGszcd() {
		return this.gszcd;
	}

	public void setGszcd(String gszcd) {
		this.gszcd = gszcd;
	}

	public String getZyjydd() {
		return this.zyjydd;
	}

	public void setZyjydd(String zyjydd) {
		this.zyjydd = zyjydd;
	}

	public String getGsclsj() {
		return this.gsclsj;
	}

	public void setGsclsj(String gsclsj) {
		this.gsclsj = gsclsj;
	}

	public String getFddbr() {
		return this.fddbr;
	}

	public void setFddbr(String fddbr) {
		this.fddbr = fddbr;
	}

	public String getNyye() {
		return this.nyye;
	}

	public void setNyye(String nyye) {
		this.nyye = nyye;
	}

	public String getYgrs() {
		return this.ygrs;
	}

	public void setYgrs(String ygrs) {
		this.ygrs = ygrs;
	}

	public String getJypp() {
		return this.jypp;
	}

	public void setJypp(String jypp) {
		this.jypp = jypp;
	}

	public String getZczb() {
		return this.zczb;
	}

	public void setZczb(String zczb) {
		this.zczb = zczb;
	}

	public String getZykhq() {
		return this.zykhq;
	}

	public void setZykhq(String zykhq) {
		this.zykhq = zykhq;
	}

	public String getZysc() {
		return this.zysc;
	}

	public void setZysc(String zysc) {
		this.zysc = zysc;
	}

	public String getNcke() {
		return this.ncke;
	}

	public void setNcke(String ncke) {
		this.ncke = ncke;
	}

	public String getNjke() {
		return this.njke;
	}

	public void setNjke(String njke) {
		this.njke = njke;
	}

	public String getKhyh() {
		return this.khyh;
	}

	public void setKhyh(String khyh) {
		this.khyh = khyh;
	}

	public String getZh() {
		return this.zh;
	}

	public void setZh(String zh) {
		this.zh = zh;
	}

	public String getOem() {
		return this.oem;
	}

	public void setOem(String oem) {
		this.oem = oem;
	}

	public String getYfbmrs() {
		return this.yfbmrs;
	}

	public void setYfbmrs(String yfbmrs) {
		this.yfbmrs = yfbmrs;
	}

	public String getYcl() {
		return this.ycl;
	}

	public void setYcl(String ycl) {
		this.ycl = ycl;
	}

	public String getCfmj() {
		return this.cfmj;
	}

	public void setCfmj(String cfmj) {
		this.cfmj = cfmj;
	}

	public String getZlkz() {
		return this.zlkz;
	}

	public void setZlkz(String zlkz) {
		this.zlkz = zlkz;
	}

	public String getGltxrz() {
		return this.gltxrz;
	}

	public void setGltxrz(String gltxrz) {
		this.gltxrz = gltxrz;
	}

	public String getGsjs() {
		return this.gsjs;
	}

	public void setGsjs(String gsjs) {
		this.gsjs = gsjs;
	}

	public String getGstp() {
		return this.gstp;
	}

	public void setGstp(String gstp) {
		this.gstp = gstp;
	}
}