package com.abbcc.pojo;

/**
 * Hyjyjl generated by MyEclipse Persistence Tools
 */

public class Hyjyjl implements java.io.Serializable {

	// Fields

	private Integer hyjyjlid;

	private Integer hyjbxxid;

	private String xxmc;

	private String xw;

	private String zy;

	private String xxksrq;

	private String xxjsrq;

	private String bz;

	// Constructors

	/** default constructor */
	public Hyjyjl() {
	}

	/** full constructor */
	public Hyjyjl(Integer hyjbxxid, String xxmc, String xw, String zy,
			String xxksrq, String xxjsrq, String bz) {
		this.hyjbxxid = hyjbxxid;
		this.xxmc = xxmc;
		this.xw = xw;
		this.zy = zy;
		this.xxksrq = xxksrq;
		this.xxjsrq = xxjsrq;
		this.bz = bz;
	}

	// Property accessors

	public Integer getHyjyjlid() {
		return this.hyjyjlid;
	}

	public void setHyjyjlid(Integer hyjyjlid) {
		this.hyjyjlid = hyjyjlid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getXxmc() {
		return this.xxmc;
	}

	public void setXxmc(String xxmc) {
		this.xxmc = xxmc;
	}

	public String getXw() {
		return this.xw;
	}

	public void setXw(String xw) {
		this.xw = xw;
	}

	public String getZy() {
		return this.zy;
	}

	public void setZy(String zy) {
		this.zy = zy;
	}

	public String getXxksrq() {
		return this.xxksrq;
	}

	public void setXxksrq(String xxksrq) {
		this.xxksrq = xxksrq;
	}

	public String getXxjsrq() {
		return this.xxjsrq;
	}

	public void setXxjsrq(String xxjsrq) {
		this.xxjsrq = xxjsrq;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}