package com.abbcc.pojo;

/**
 * Jytj generated by MyEclipse Persistence Tools
 */

public class Jytj implements java.io.Serializable {

	// Fields

	private Integer jytjid;

	private Integer hyjbxxid;

	private String jldw;

	private String cpdj;

	private String zxqdl;

	private String ghzl;

	private String fhqx;

	private String gyslc;

	// Constructors

	/** default constructor */
	public Jytj() {
	}

	/** full constructor */
	public Jytj(Integer hyjbxxid, String jldw, String cpdj, String zxqdl,
			String ghzl, String fhqx, String gyslc) {
		this.hyjbxxid = hyjbxxid;
		this.jldw = jldw;
		this.cpdj = cpdj;
		this.zxqdl = zxqdl;
		this.ghzl = ghzl;
		this.fhqx = fhqx;
		this.gyslc = gyslc;
	}

	// Property accessors

	public Integer getJytjid() {
		return this.jytjid;
	}

	public void setJytjid(Integer jytjid) {
		this.jytjid = jytjid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getJldw() {
		return this.jldw;
	}

	public void setJldw(String jldw) {
		this.jldw = jldw;
	}

	public String getCpdj() {
		return this.cpdj;
	}

	public void setCpdj(String cpdj) {
		this.cpdj = cpdj;
	}

	public String getZxqdl() {
		return this.zxqdl;
	}

	public void setZxqdl(String zxqdl) {
		this.zxqdl = zxqdl;
	}

	public String getGhzl() {
		return this.ghzl;
	}

	public void setGhzl(String ghzl) {
		this.ghzl = ghzl;
	}

	public String getFhqx() {
		return this.fhqx;
	}

	public void setFhqx(String fhqx) {
		this.fhqx = fhqx;
	}

	public String getGyslc() {
		return this.gyslc;
	}

	public void setGyslc(String gyslc) {
		this.gyslc = gyslc;
	}

}