package com.abbcc.pojo;

/**
 * PzId generated by MyEclipse Persistence Tools
 */

public class Pz implements java.io.Serializable {

	// Fields

	private String tablename;

	private Integer recnum;

	// Constructors

	/** default constructor */
	public Pz() {
	}

	/** full constructor */
	public Pz(String tablename, Integer recnum, Integer recnum2) {
		this.tablename = tablename;
		this.recnum = recnum;
	}

	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public Integer getRecnum() {
		return recnum;
	}

	public void setRecnum(Integer recnum) {
		this.recnum = recnum;
	}


}