package com.abbcc.pojo;

/**
 * Gsjbxx generated by MyEclipse Persistence Tools
 */

public class Gsjbxx implements java.io.Serializable {

	// Fields

	private Integer hyjbxxid;

	private String gslx;

	private String gsmc;

	private String gsyymc;

	private String gj;

	private String sf;

	private String djs;

	private String xjs;

	private String jydz;

	private String zyhy;

	private String zyfx;

	private String xsdcp;

	private String cgdcp;

	// Constructors

	/** default constructor */
	public Gsjbxx() {
	}

	/** full constructor */
	public Gsjbxx(Integer hyjbxxid, String gslx, String gsmc, String gsyymc,
			String gj, String sf, String djs, String xjs, String jydz,
			String zyhy, String zyfx, String xsdcp, String cgdcp) {
		this.hyjbxxid = hyjbxxid;
		this.gslx = gslx;
		this.gsmc = gsmc;
		this.gsyymc = gsyymc;
		this.gj = gj;
		this.sf = sf;
		this.djs = djs;
		this.xjs = xjs;
		this.jydz = jydz;
		this.zyhy = zyhy;
		this.zyfx = zyfx;
		this.xsdcp = xsdcp;
		this.cgdcp = cgdcp;
	}

	// Property accessors

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getGslx() {
		return this.gslx;
	}

	public void setGslx(String gslx) {
		this.gslx = gslx;
	}

	public String getGsmc() {
		return this.gsmc;
	}

	public void setGsmc(String gsmc) {
		this.gsmc = gsmc;
	}

	public String getGsyymc() {
		return this.gsyymc;
	}

	public void setGsyymc(String gsyymc) {
		this.gsyymc = gsyymc;
	}

	public String getGj() {
		return this.gj;
	}

	public void setGj(String gj) {
		this.gj = gj;
	}

	public String getSf() {
		return this.sf;
	}

	public void setSf(String sf) {
		this.sf = sf;
	}

	public String getDjs() {
		return this.djs;
	}

	public void setDjs(String djs) {
		this.djs = djs;
	}

	public String getXjs() {
		return this.xjs;
	}

	public void setXjs(String xjs) {
		this.xjs = xjs;
	}

	public String getJydz() {
		return this.jydz;
	}

	public void setJydz(String jydz) {
		this.jydz = jydz;
	}

	public String getZyhy() {
		return this.zyhy;
	}

	public void setZyhy(String zyhy) {
		this.zyhy = zyhy;
	}

	public String getZyfx() {
		return this.zyfx;
	}

	public void setZyfx(String zyfx) {
		this.zyfx = zyfx;
	}

	public String getXsdcp() {
		return this.xsdcp;
	}

	public void setXsdcp(String xsdcp) {
		this.xsdcp = xsdcp;
	}

	public String getCgdcp() {
		return this.cgdcp;
	}

	public void setCgdcp(String cgdcp) {
		this.cgdcp = cgdcp;
	}
}