package com.abbcc.pojo;

/**
 * Hygrzl generated by MyEclipse Persistence Tools
 */

public class Hygrzl implements java.io.Serializable {

	// Fields

	private Integer hyjbxxid;

	private String sr;

	private String xx;

	private String jg;

	private String slsp;

	private String xl;

	private String zjxy;

	private String grzy;

	private String xqah;

	private String zwjs;

	// Constructors

	/** default constructor */
	public Hygrzl() {
	}

	/** full constructor */
	public Hygrzl(String sr, String xx, String jg, String slsp, String xl,
			String zjxy, String grzy, String xqah, String zwjs) {
		this.sr = sr;
		this.xx = xx;
		this.jg = jg;
		this.slsp = slsp;
		this.xl = xl;
		this.zjxy = zjxy;
		this.grzy = grzy;
		this.xqah = xqah;
		this.zwjs = zwjs;
	}

	// Property accessors

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getSr() {
		return this.sr;
	}

	public void setSr(String sr) {
		this.sr = sr;
	}

	public String getXx() {
		return this.xx;
	}

	public void setXx(String xx) {
		this.xx = xx;
	}

	public String getJg() {
		return this.jg;
	}

	public void setJg(String jg) {
		this.jg = jg;
	}

	public String getSlsp() {
		return this.slsp;
	}

	public void setSlsp(String slsp) {
		this.slsp = slsp;
	}

	public String getXl() {
		return this.xl;
	}

	public void setXl(String xl) {
		this.xl = xl;
	}

	public String getZjxy() {
		return this.zjxy;
	}

	public void setZjxy(String zjxy) {
		this.zjxy = zjxy;
	}

	public String getGrzy() {
		return this.grzy;
	}

	public void setGrzy(String grzy) {
		this.grzy = grzy;
	}

	public String getXqah() {
		return this.xqah;
	}

	public void setXqah(String xqah) {
		this.xqah = xqah;
	}

	public String getZwjs() {
		return this.zwjs;
	}

	public void setZwjs(String zwjs) {
		this.zwjs = zwjs;
	}

}