package com.abbcc.pojo;

/**
 * Hygzjl generated by MyEclipse Persistence Tools
 */

public class Hygzjl implements java.io.Serializable {

	// Fields

	private Integer hygzjlid;

	private Integer hyjbxxid;

	private String rzrq;

	private String gs;

	private String sshy;

	private String gm;

	private String bm;

	private String zw;

	private String gznr;

	// Constructors

	/** default constructor */
	public Hygzjl() {
	}

	/** full constructor */
	public Hygzjl(Integer hyjbxxid, String rzrq, String gs, String sshy,
			String gm, String bm, String zw, String gznr) {
		this.hyjbxxid = hyjbxxid;
		this.rzrq = rzrq;
		this.gs = gs;
		this.sshy = sshy;
		this.gm = gm;
		this.bm = bm;
		this.zw = zw;
		this.gznr = gznr;
	}

	// Property accessors

	public Integer getHygzjlid() {
		return this.hygzjlid;
	}

	public void setHygzjlid(Integer hygzjlid) {
		this.hygzjlid = hygzjlid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getRzrq() {
		return this.rzrq;
	}

	public void setRzrq(String rzrq) {
		this.rzrq = rzrq;
	}

	public String getGs() {
		return this.gs;
	}

	public void setGs(String gs) {
		this.gs = gs;
	}

	public String getSshy() {
		return this.sshy;
	}

	public void setSshy(String sshy) {
		this.sshy = sshy;
	}

	public String getGm() {
		return this.gm;
	}

	public void setGm(String gm) {
		this.gm = gm;
	}

	public String getBm() {
		return this.bm;
	}

	public void setBm(String bm) {
		this.bm = bm;
	}

	public String getZw() {
		return this.zw;
	}

	public void setZw(String zw) {
		this.zw = zw;
	}

	public String getGznr() {
		return this.gznr;
	}

	public void setGznr(String gznr) {
		this.gznr = gznr;
	}

}