package com.abbcc.pojo;

/**
 * Fwsx generated by MyEclipse Persistence Tools
 */

public class Fwsx implements java.io.Serializable {

	// Fields

	private Integer fwsxid;

	private Integer hyjbxxid;

	private String xxsm;

	private String tp1;

	private String tp2;

	private String tp3;

	private String xxyxq;

	private String sqsj;

	private String sfyx;

	private String scsj;

	// Constructors

	/** default constructor */
	public Fwsx() {
	}

	/** full constructor */
	public Fwsx(Integer hyjbxxid, String xxsm, String tp1, String tp2,
			String tp3, String xxyxq, String sqsj, String sfyx, String scsj) {
		this.hyjbxxid = hyjbxxid;
		this.xxsm = xxsm;
		this.tp1 = tp1;
		this.tp2 = tp2;
		this.tp3 = tp3;
		this.xxyxq = xxyxq;
		this.sqsj = sqsj;
		this.sfyx = sfyx;
		this.scsj = scsj;
	}

	// Property accessors

	public Integer getFwsxid() {
		return this.fwsxid;
	}

	public void setFwsxid(Integer fwsxid) {
		this.fwsxid = fwsxid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getXxsm() {
		return this.xxsm;
	}

	public void setXxsm(String xxsm) {
		this.xxsm = xxsm;
	}

	public String getTp1() {
		return this.tp1;
	}

	public void setTp1(String tp1) {
		this.tp1 = tp1;
	}

	public String getTp2() {
		return this.tp2;
	}

	public void setTp2(String tp2) {
		this.tp2 = tp2;
	}

	public String getTp3() {
		return this.tp3;
	}

	public void setTp3(String tp3) {
		this.tp3 = tp3;
	}

	public String getXxyxq() {
		return this.xxyxq;
	}

	public void setXxyxq(String xxyxq) {
		this.xxyxq = xxyxq;
	}

	public String getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}

	public String getSfyx() {
		return this.sfyx;
	}

	public void setSfyx(String sfyx) {
		this.sfyx = sfyx;
	}

	public String getScsj() {
		return this.scsj;
	}

	public void setScsj(String scsj) {
		this.scsj = scsj;
	}

}