package com.abbcc.pojo;

/**
 * Honor generated by MyEclipse Persistence Tools
 */

/**
 * @author 姜志强
 *  公司荣誉证书信息
 *  create at 2009-1-14
 */
public class Honor implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = -3753356685294950668L;
	
	private Integer hyjbxxid;
	//文件存放路径
	//private String place;
	//荣誉信息
	private String  honorInfo;

	private String createTime;

	// Constructors

	/** default constructor */
	public Honor() {
	}

	/** minimal constructor */
	public Honor(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	/** full constructor */
	public Honor(Integer hyjbxxid, String honorInfo, String createTime) {
		this.hyjbxxid = hyjbxxid;
		this.honorInfo = honorInfo;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getHonorInfo() {
		return this.honorInfo;
	}

	public void setHonorInfo(String honorInfo) {
		this.honorInfo = honorInfo;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}