package com.abbcc.pojo;

/**
 * Jghz generated by MyEclipse Persistence Tools
 */

public class Jghz implements java.io.Serializable {

	// Fields

	private Integer jghzid;

	private Integer hyjbxxid;

	private String jglx;

	private String jgmc;

	private String jgsslm;

	private String sqsj;

	private String sfyx;

	private String scsj;

	// Constructors

	/** default constructor */
	public Jghz() {
	}

	/** full constructor */
	public Jghz(Integer hyjbxxid, String jglx, String jgmc, String jgsslm,
			String sqsj, String sfyx, String scsj) {
		this.hyjbxxid = hyjbxxid;
		this.jglx = jglx;
		this.jgmc = jgmc;
		this.jgsslm = jgsslm;
		this.sqsj = sqsj;
		this.sfyx = sfyx;
		this.scsj = scsj;
	}

	// Property accessors

	public Integer getJghzid() {
		return this.jghzid;
	}

	public void setJghzid(Integer jghzid) {
		this.jghzid = jghzid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getJglx() {
		return this.jglx;
	}

	public void setJglx(String jglx) {
		this.jglx = jglx;
	}

	public String getJgmc() {
		return this.jgmc;
	}

	public void setJgmc(String jgmc) {
		this.jgmc = jgmc;
	}

	public String getJgsslm() {
		return this.jgsslm;
	}

	public void setJgsslm(String jgsslm) {
		this.jgsslm = jgsslm;
	}

	public String getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}

	public String getSfyx() {
		return this.sfyx;
	}

	public void setSfyx(String sfyx) {
		this.sfyx = sfyx;
	}

	public String getScsj() {
		return this.scsj;
	}

	public void setScsj(String scsj) {
		this.scsj = scsj;
	}

}