package com.abbcc.pojo;

/**
 * Wzjbxx generated by MyEclipse Persistence Tools
 */

public class Wzjbxx implements java.io.Serializable {

	// Fields

	private Integer glyid;

	private String wzmc;

	private String wz;

	private String gsmc;

	private String yb;

	private String lxdh;

	private String cz;

	private String dzyxs;

	private String dzyxt;

	private String lxr;

	private String qq;

	private String hysh;

	private String xxsh;

	private String cpsh;

	private String zpsh;

	// Constructors

	/** default constructor */
	public Wzjbxx() {
	}

	/** full constructor */
	public Wzjbxx(String wzmc, String wz, String gsmc, String yb, String lxdh,
			String cz, String dzyxs, String dzyxt, String lxr, String qq,
			String hysh, String xxsh, String cpsh, String zpsh) {
		this.wzmc = wzmc;
		this.wz = wz;
		this.gsmc = gsmc;
		this.yb = yb;
		this.lxdh = lxdh;
		this.cz = cz;
		this.dzyxs = dzyxs;
		this.dzyxt = dzyxt;
		this.lxr = lxr;
		this.qq = qq;
		this.hysh = hysh;
		this.xxsh = xxsh;
		this.cpsh = cpsh;
		this.zpsh = zpsh;
	}

	// Property accessors

	public Integer getGlyid() {
		return this.glyid;
	}

	public void setGlyid(Integer glyid) {
		this.glyid = glyid;
	}

	public String getWzmc() {
		return this.wzmc;
	}

	public void setWzmc(String wzmc) {
		this.wzmc = wzmc;
	}

	public String getWz() {
		return this.wz;
	}

	public void setWz(String wz) {
		this.wz = wz;
	}

	public String getGsmc() {
		return this.gsmc;
	}

	public void setGsmc(String gsmc) {
		this.gsmc = gsmc;
	}

	public String getYb() {
		return this.yb;
	}

	public void setYb(String yb) {
		this.yb = yb;
	}

	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	public String getCz() {
		return this.cz;
	}

	public void setCz(String cz) {
		this.cz = cz;
	}

	public String getDzyxs() {
		return this.dzyxs;
	}

	public void setDzyxs(String dzyxs) {
		this.dzyxs = dzyxs;
	}

	public String getDzyxt() {
		return this.dzyxt;
	}

	public void setDzyxt(String dzyxt) {
		this.dzyxt = dzyxt;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getHysh() {
		return this.hysh;
	}

	public void setHysh(String hysh) {
		this.hysh = hysh;
	}

	public String getXxsh() {
		return this.xxsh;
	}

	public void setXxsh(String xxsh) {
		this.xxsh = xxsh;
	}

	public String getCpsh() {
		return this.cpsh;
	}

	public void setCpsh(String cpsh) {
		this.cpsh = cpsh;
	}

	public String getZpsh() {
		return this.zpsh;
	}

	public void setZpsh(String zpsh) {
		this.zpsh = zpsh;
	}

}