package com.abbcc.pojo;

/**
 * Xxsh generated by MyEclipse Persistence Tools
 */

public class Xxsh implements java.io.Serializable {

	// Fields

	private Integer glyid;

	private Integer xxid;

	private String fbr;

	private String fbrq;

	private String sfsh;

	private String shlx;

	// Constructors

	/** default constructor */
	public Xxsh() {
	}

	/** full constructor */
	public Xxsh(Integer xxid, String fbr, String fbrq, String sfsh, String shlx) {
		this.xxid = xxid;
		this.fbr = fbr;
		this.fbrq = fbrq;
		this.sfsh = sfsh;
		this.shlx = shlx;
	}

	// Property accessors

	public Integer getGlyid() {
		return this.glyid;
	}

	public void setGlyid(Integer glyid) {
		this.glyid = glyid;
	}

	public Integer getXxid() {
		return this.xxid;
	}

	public void setXxid(Integer xxid) {
		this.xxid = xxid;
	}

	public String getFbr() {
		return this.fbr;
	}

	public void setFbr(String fbr) {
		this.fbr = fbr;
	}

	public String getFbrq() {
		return this.fbrq;
	}

	public void setFbrq(String fbrq) {
		this.fbrq = fbrq;
	}

	public String getSfsh() {
		return this.sfsh;
	}

	public void setSfsh(String sfsh) {
		this.sfsh = sfsh;
	}

	public String getShlx() {
		return this.shlx;
	}

	public void setShlx(String shlx) {
		this.shlx = shlx;
	}

}