package com.abbcc.pojo;

/**
 * Gly generated by MyEclipse Persistence Tools
 */

public class Gly implements java.io.Serializable {

	// Fields

	private Integer glyid;

	private String yhm;

	private String mm;

	private String zhdlsj;

	private String zhdlip;

	private String glqx;

	// Constructors

	/** default constructor */
	public Gly() {
	}

	/** full constructor */
	public Gly(String yhm, String mm, String zhdlsj, String zhdlip, String glqx) {
		this.yhm = yhm;
		this.mm = mm;
		this.zhdlsj = zhdlsj;
		this.zhdlip = zhdlip;
		this.glqx = glqx;
	}

	// Property accessors

	public Integer getGlyid() {
		return this.glyid;
	}

	public void setGlyid(Integer glyid) {
		this.glyid = glyid;
	}

	public String getYhm() {
		return this.yhm;
	}

	public void setYhm(String yhm) {
		this.yhm = yhm;
	}

	public String getMm() {
		return this.mm;
	}

	public void setMm(String mm) {
		this.mm = mm;
	}

	public String getZhdlsj() {
		return this.zhdlsj;
	}

	public void setZhdlsj(String zhdlsj) {
		this.zhdlsj = zhdlsj;
	}

	public String getZhdlip() {
		return this.zhdlip;
	}

	public void setZhdlip(String zhdlip) {
		this.zhdlip = zhdlip;
	}

	public String getGlqx() {
		return this.glqx;
	}

	public void setGlqx(String glqx) {
		this.glqx = glqx;
	}

}