package com.abbcc.pojo;

/**
 * Zpxx generated by MyEclipse Persistence Tools
 */

public class Zpxx implements java.io.Serializable {

	// Fields

	private Integer zpxxid;

	private Integer hyjbxxid;

	private String zpzt;

	private String yxq;

	private String hy;

	private String gshy;

	private String gzdd;

	private String zprs;

	private String gznx;

	private String xzsp;

	private String zwyq;

	private String lxr;

	private String lxfs;

	private String bz;

	private String sqsj;

	private String sfyx;

	private String scsj;

	// Constructors

	/** default constructor */
	public Zpxx() {
	}

	/** full constructor */
	public Zpxx(Integer hyjbxxid, String zpzt, String yxq, String hy,
			String gshy, String gzdd, String zprs, String gznx, String xzsp,
			String zwyq, String lxr, String lxfs, String bz, String sqsj,
			String sfyx, String scsj) {
		this.hyjbxxid = hyjbxxid;
		this.zpzt = zpzt;
		this.yxq = yxq;
		this.hy = hy;
		this.gshy = gshy;
		this.gzdd = gzdd;
		this.zprs = zprs;
		this.gznx = gznx;
		this.xzsp = xzsp;
		this.zwyq = zwyq;
		this.lxr = lxr;
		this.lxfs = lxfs;
		this.bz = bz;
		this.sqsj = sqsj;
		this.sfyx = sfyx;
		this.scsj = scsj;
	}

	// Property accessors

	public Integer getZpxxid() {
		return this.zpxxid;
	}

	public void setZpxxid(Integer zpxxid) {
		this.zpxxid = zpxxid;
	}

	public Integer getHyjbxxid() {
		return this.hyjbxxid;
	}

	public void setHyjbxxid(Integer hyjbxxid) {
		this.hyjbxxid = hyjbxxid;
	}

	public String getZpzt() {
		return this.zpzt;
	}

	public void setZpzt(String zpzt) {
		this.zpzt = zpzt;
	}

	public String getYxq() {
		return this.yxq;
	}

	public void setYxq(String yxq) {
		this.yxq = yxq;
	}

	public String getHy() {
		return this.hy;
	}

	public void setHy(String hy) {
		this.hy = hy;
	}

	public String getGshy() {
		return this.gshy;
	}

	public void setGshy(String gshy) {
		this.gshy = gshy;
	}

	public String getGzdd() {
		return this.gzdd;
	}

	public void setGzdd(String gzdd) {
		this.gzdd = gzdd;
	}

	public String getZprs() {
		return this.zprs;
	}

	public void setZprs(String zprs) {
		this.zprs = zprs;
	}

	public String getGznx() {
		return this.gznx;
	}

	public void setGznx(String gznx) {
		this.gznx = gznx;
	}

	public String getXzsp() {
		return this.xzsp;
	}

	public void setXzsp(String xzsp) {
		this.xzsp = xzsp;
	}

	public String getZwyq() {
		return this.zwyq;
	}

	public void setZwyq(String zwyq) {
		this.zwyq = zwyq;
	}

	public String getLxr() {
		return this.lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	public String getLxfs() {
		return this.lxfs;
	}

	public void setLxfs(String lxfs) {
		this.lxfs = lxfs;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getSqsj() {
		return this.sqsj;
	}

	public void setSqsj(String sqsj) {
		this.sqsj = sqsj;
	}

	public String getSfyx() {
		return this.sfyx;
	}

	public void setSfyx(String sfyx) {
		this.sfyx = sfyx;
	}

	public String getScsj() {
		return this.scsj;
	}

	public void setScsj(String scsj) {
		this.scsj = scsj;
	}

}